# Generated by Django 5.2.1 on 2025-05-28 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Částka"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Paid", "Zaplaceno"), ("Unpaid", "Nezaplaceno")],
                        max_length=15,
                        verbose_name="Stav platby",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Datum platby")),
                ("QR_code", models.CharField(max_length=255, verbose_name="QR kód")),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="events.event",
                        verbose_name="id_události",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="id_uživatele",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platba",
                "verbose_name_plural": "Platby",
                "ordering": ["payment_date"],
                "unique_together": {("id_user", "id_event")},
            },
        ),
    ]
