# Generated by Django 5.2.1 on 2025-05-28 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        ("payments", "0001_initial"),
        ("registrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="id_registration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="registrations.registration",
                verbose_name="id_registrace",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id_event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="events.event",
                verbose_name="id_události",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="id_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="id_uživatele",
            ),
        ),
    ]
