# Generated by Django 5.1.1 on 2025-05-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(choices=[("M", "Muž"), ("F", "Žena")], max_length=1),
        ),
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.URLField(),
        ),
    ]
