# Generated by Django 5.1.1 on 2025-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_organization_name_user_unique_email_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
