# Generated by Django 5.1.1 on 2025-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_website"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_role",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
