# Generated by Django 5.1.1 on 2025-05-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_event", models.DateField(verbose_name="Datum události")),
                (
                    "name_event",
                    models.CharField(max_length=30, verbose_name="Název události"),
                ),
                ("description", models.TextField(verbose_name="Popis události")),
                ("start_time", models.DateTimeField(verbose_name="Čas startu")),
                ("distance", models.IntegerField(verbose_name="Vzdálenost")),
                ("country", models.CharField(max_length=50, verbose_name="Země")),
                ("city", models.CharField(max_length=50, verbose_name="Město")),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("hlavní město Praha", "hlavní město Praha"),
                            ("Středočeský kraj", "Středočeský kraj"),
                            ("Jihočeský kraj", "Jihočeský kraj"),
                            ("Plzeňský kraj", "Plzeňský kraj"),
                            ("Karlovarský kraj", "Karlovarský kraj"),
                            ("Ústecký kraj", "Ústecký kraj"),
                            ("Liberecký kraj", "Liberecký kraj"),
                            ("Královéhradecký kraj", "Královéhradecký kraj"),
                            ("Pardubický kraj", "Pardubický kraj"),
                            ("Kraj Vysočina", "Kraj Vysočina"),
                            ("Jihomoravský kraj", "Jihomoravský kraj"),
                            ("Olomoucký kraj", "Olomoucký kraj"),
                            ("Moravskoslezský kraj", "Moravskoslezský kraj"),
                            ("Zlínský kraj", "Zlínský kraj"),
                        ],
                        max_length=100,
                        verbose_name="Kraj",
                    ),
                ),
                (
                    "typ_race",
                    models.CharField(
                        choices=[
                            ("Silnice", "Silnice"),
                            ("Trail", "Trail"),
                            ("Mix", "Smíšený"),
                        ],
                        max_length=7,
                        verbose_name="Typ závodu - povrch",
                    ),
                ),
                (
                    "propozition",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Propozice"
                    ),
                ),
                (
                    "start_fee",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Startovné"
                    ),
                ),
            ],
            options={
                "ordering": ["date_event"],
            },
        ),
    ]
