# Generated by Django 5.2.1 on 2025-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(verbose_name="Čas startu"),
        ),
    ]
