# Generated by Django 5.1.1 on 2025-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_start_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
        migrations.AlterField(
            model_name="event",
            name="name_event",
            field=models.CharField(max_length=100, verbose_name="Název události"),
        ),
    ]
