# Generated by Django 5.1.1 on 2025-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_options_remove_event_organizer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name_event",
            field=models.CharField(max_length=255, verbose_name="Název události"),
        ),
    ]
