# Generated by Django 5.2.1 on 2025-05-28 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Datum registrace"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("M40", "Muži do 40 let "),
                            ("V", "Veteráni"),
                            ("W40", "Ženy do 40 let"),
                            ("W0", "Veteránky"),
                            ("Junior", "Dorostenci"),
                        ],
                        max_length=7,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="id_události",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="id_uživatele",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registrace",
                "verbose_name_plural": "Registrace",
                "ordering": ["registration_date"],
                "unique_together": {("id_user", "id_event")},
            },
        ),
    ]
